name: core # this will be used to save model
type: sci
train:
  supervised: False
  n_gram_range: # Give a range here. In example here, we use ngram from 1-3
    - 1
    - 3
  embedding_model: all-MiniLM-L6-v2

  cluster:
    hdbscan:
      min_cluster_size: 30
      min_samples: 30
      metric: euclidean
      cluster_selection_method: eom
      prediction_data: True
      gen_min_span_tree: True
  bertopic:
    calculate_probabilities: True
    verbose: True
    #nr_topics: 80
    language: multilingual

find_optimal_topic_first:
  config_path: ./configs/evaluate/lda.yaml

save: True
model_path: ./models

