dataset:
  data_file: ./data/model_data/SUS-SCI_PDFS_TM.json
  topic_name: SUS-SCI_PDFS_TM
  raw_data:
    data_path: ./data/strandbox_jsons
    type: sci # For now only two types are supported: tweet or sci

train:
  supervised: False
  n_gram_range: # Give a range here. In example here, we use ngram from 1-3
    - 1
    - 3
  sentence_model:
    name: allenai/scibert_scivocab_uncased
    max_seq_len: 512
  dim_reduct:
    umap:
      n_neighbors: 15
      n_components: 10
      min_dist: 0.0
      metric: cosine
      #low_memory: False
  cluster:
    hdbscan:
      min_cluster_size: 10
      min_samples: 1
      metric: euclidean
      cluster_selection_method: eom
      prediction_data: True
  bertopic:
    calculate_probabilities: True
    verbose: True
    #nr_topics: 80
    language: multilingual

eval: False
save: True
model_path: ./models

